# Generated by Django 3.2.8 on 2021-12-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contemt',
            new_name='content',
        ),
    ]
